# vi: filetype=yaml
# spellchecker: disable
---
CompileFlags:
  Add:
    - -ferror-limit=0
    - -Weverything
    - -Werror
    - -Wno-c++98-compat
    - -Wno-c++98-compat-pedantic
  Remove:
    - -W*
